steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/bank-transactions-api-$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/bank-transactions-api-$COMMIT_SHA']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'bank-transactions-api', '--image', 'gcr.io/$PROJECT_ID/bank-transactions-api-$COMMIT_SHA', '--region', 'europe-west6']
images:
- gcr.io/$PROJECT_ID/bank-transactions-api-$COMMIT_SHA