version: "3"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: your-database-name
      MYSQL_USER: your-username
      MYSQL_PASSWORD: your-password
      MYSQL_ROOT_PASSWORD: your-root-password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
